name: release

on:
  push:
    tags:
      - "etcd-manager-bp/v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push etcd-manager images
        run: |
          VERSION=$(echo $GITHUB_REF_NAME | sed s@etcd-manager-bp/@@g)

          export DOCKER_REGISTRY=ghcr.io
          export DOCKER_IMAGE_PREFIX=ederst/
          export DOCKER_TAG=${VERSION}
          make -C etcd-manager push

      # TODO: make artifacts available on github?
      # - name: Build etcd-manager assets
      #   run: |
      #     ./dev/build-assets.sh ${GITHUB_REF_NAME}
      #   working-directory: ./etcd-manager/

